### PR TITLE
Fix #3592. Bad Input Error if pbjs s2s config contains alias configuration for a disabled adapter

### LINKED ISSUE #3592: Bad Input Error if pbjs s2s config contains alias configuration for a disabled adapter
Deploying `alias` configurations for prebid server through prebid.js is dangerous, because if a bidder is being disabled, it can stop the entire monetization of prebid server. Disabled bidders will stop the entire bid requests with a `400` if the alias configuration contains a disabled bidder.

## :magic_wand:  Steps to reproduce

Prebid.js `s2s` config

```javascript
    s2sConfig: [
      // Server side only configuration
      {
        accountId: accountId,
        adapter: 'prebidServer',
        endpoint: { p1Consent: 'https://prebid-server/openrtb2/auction' },
        syncEndpoint: { p1Consent: 'https://prebid-server/cookie_sync' },
        bidders: [ 'bidderA', 'bidderB' ],
        extPrebid: {
          aliases: {
            'bidder_c_alias': 'bidder_c' // note that this bidder isn't even in the bidders array
          }
        }
      }
    ],
```

and send a request to a prebid server where `BidderC` is not enabled.

This will cause a `400` with

```
Invalid request format: request.ext.prebid.aliases.bidder_c_alias refers to disabled bidder: bidder_c
```

## :bulb: Proposal

We turn the 400 into an error metric. Related to #3209

## Related

If the bidder being alias is unknown also a `400` is being returned:

```
Invalid request format: request.ext.prebid.aliases.bidder_c_alias refers to unknown bidder: bidder_c
```

which I guess is okaish, but a metric would also be better.

### PR DESCRIPTION
**Pull request by zxPhoenix**
### 🔧 Type of changes
- [ ] new bid adapter
- [ ] bid adapter update
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] module update
- [x] bugfix
- [ ] documentation
- [ ] configuration
- [ ] dependency update
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?
Fix [issue #3592](https://github.com/prebid/prebid-server-java/issues/3592). Bad Input Error if pbjs s2s config contains alias configuration for a disabled adapter.
Move unknown bidder and bidder is deactivated errors to warnings level.
Add unknown_bidder and deactivated_bidder metrics
 

### 🧠 Rationale behind the change
Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hostnames
- [ ] geographic host parameters are NOT required
- [ ] direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan
Changes are covered by unit tests.

### 🏎 Quality check
- [x] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [x] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

### CODE REVIEW

File: src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java [hunk 1]
```diff
@@ -111,6 +112,7 @@ public Future<WithPodErrors<AuctionContext>> fromRequest(RoutingContext routingC
                 .compose(httpRequest -> createBidRequest(httpRequest)
                         .map(bidRequest -> removeEmptyEids(bidRequest, initialAuctionContext.getDebugWarnings()))
                         .compose(bidRequest -> validateRequest(
+                                initialAuctionContext.getAccount(),
```
Comment (CTMBNara) [inline src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java:115]: `initialAuctionContext.getAccount()` will always return `null` here

File: src/main/java/org/prebid/server/metric/Metrics.java [hunk 2]
```diff
@@ -329,6 +329,22 @@ public void updateAdapterRequestErrorMetric(String bidder, MetricName errorMetri
...
+        }
+    }
+
+    public void updateAdapterRequestUnknownBidderMetric(String bidder, Account account) {
+        forAdapter(bidder).request().incCounter(MetricName.unknown_bidder);
+        if (accountMetricsVerbosityResolver.forAccount(account)
+                .isAtLeast(AccountMetricsVerbosityLevel.detailed)) {
+            forAccount(account.getId()).adapter().forAdapter(bidder).request().incCounter(MetricName.unknown_bidder);
+        }
+    }
```
Comment (CTMBNara) [inline src/main/java/org/prebid/server/metric/Metrics.java:346]: I don't like this solution. Someone can spam the server with invalid bidders and load the memory by creating new entries in the map (with many invalid bidders).

**Review by CTMBNara — CHANGES_REQUESTED** [review]

File: src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java (hunk 1 above)
Comment (CTMBNara) [reply src/main/java/org/prebid/server/auction/requestfactory/VideoRequestFactory.java:115]: I think we can accept it this way, since we haven't supported Video endpoint for many months now.

**Comment by osulzhenko** [comment]
@zxPhoenix could you please update this PR?

**Comment by zxPhoenix** [comment]
> @zxPhoenix could you please update this PR?

Sure. Sorry for the delay. I have prioritised this PR.

File: src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java [hunk 3]
```diff
@@ -1033,15 +1033,19 @@ RequestValidator requestValidator(
             Metrics metrics,
             JacksonMapper mapper,
             @Value("${logging.sampling-rate:0.01}") double logSamplingRate,
-            @Value("${auction.strict-app-site-dooh:false}") boolean enabledStrictAppSiteDoohValidation) {
+            @Value("${auction.strict-app-site-dooh:false}") boolean enabledStrictAppSiteDoohValidation,
+            @Value("${settings.fail-on-disabled-bidders}") boolean failOnDisabledBidders,
+            @Value("${settings.fail-on-unknown-bidders}") boolean failOnUnknownBidders) {
```
Comment (CTMBNara) [inline src/main/java/org/prebid/server/spring/config/ServiceConfiguration.java:1038]: Please, add default values as on line above

File: src/main/java/org/prebid/server/validation/RequestValidator.java [hunk 4]
```diff
@@ -505,18 +513,34 @@ private static void validateGranularityRangeIncrement(ExtGranularityRange range)
      * Validates aliases. Throws {@link ValidationException} in cases when alias points to invalid bidder or when alias
      * is equals to itself.
      */
-    private void validateAliases(Map<String, String> aliases) throws ValidationException {
+    private void validateAliases(Map<String, String> aliases, List<String> warnings,
+                                 Metrics metrics, Account account) throws ValidationException {
```
Comment (CTMBNara) [inline src/main/java/org/prebid/server/validation/RequestValidator.java:517]: No need to pass `Metrics` here, it's not a static method

File: src/main/java/org/prebid/server/validation/RequestValidator.java [hunk 5]
```diff
@@ -505,18 +513,34 @@ private static void validateGranularityRangeIncrement(ExtGranularityRange range)
...
-                throw new ValidationException(
-                        "request.ext.prebid.aliases.%s refers to unknown bidder: %s".formatted(alias, coreBidder));
-            }
-            if (!bidderCatalog.isActive(coreBidder)) {
-                throw new ValidationException(
-                        "request.ext.prebid.aliases.%s refers to disabled bidder: %s".formatted(alias, coreBidder));
+                metrics.updateUnknownBidderMetric(account);
+
+                final String message = String.format("request.ext.prebid.aliases.%s refers to unknown bidder: %s",
+                        alias, coreBidder);
```
Comment (CTMBNara) [inline src/main/java/org/prebid/server/validation/RequestValidator.java:526]:
```
"request.ext.prebid.aliases.%s refers to unknown bidder: %s".format(alias, coreBidder);
```

File: src/main/java/org/prebid/server/validation/RequestValidator.java [hunk 6]
```diff
@@ -505,18 +513,34 @@ private static void validateGranularityRangeIncrement(ExtGranularityRange range)
...
+                if (failOnUnknownBidders) {
+                    throw new ValidationException(message);
+                } else {
+                    warnings.add(message);
+                }
+            } else if (!bidderCatalog.isActive(coreBidder)) {
+                metrics.updateDisabledBidderMetric(account);
+
+                final String message = String.format("request.ext.prebid.aliases.%s refers to disabled bidder: %s",
+                        alias, coreBidder);
```
Comment (CTMBNara) [inline src/main/java/org/prebid/server/validation/RequestValidator.java:536]: same here

**Review by CTMBNara — CHANGES_REQUESTED** [review]

**Review by CTMBNara — APPROVED** [review]
