### PR TITLE
IX adapter: Handle missing interstitial formats

### LINKED ISSUE #4325: IX adapter crashes when there is no interstitial size
# Complaint

Mobile pubs sometimes report a crash on interstitial requests like:
```
500 error type: Critical error while running the auction: null
```
(talk to me in Prebid Slack I'll give you a curl)

# Root cause analysis

`formats` is not null-checked here in the Index Exchange adapter: https://github.com/prebid/prebid-server-java/blob/01acd952715516a4c80be35f5f1d7fa915e635ad/src/main/java/org/prebid/server/bidder/ix/IxBidder.java#L154

and it causes a crash when there was no `formats` specified and no matching sizes were computed due to `device.ext.prebid.interstitial.min[width/height]perc` being too high or not specified.  `imp` will be returned unaltered from here in either of those cases: https://github.com/prebid/prebid-server-java/blob/01acd952715516a4c80be35f5f1d7fa915e635ad/src/main/java/org/prebid/server/auction/InterstitialProcessor.java#L83

# Fix options
1. implement a null check and a test case (but other adapters may have similar failures, thus see option 2)
2. ensure `formats` is always an array before sending it to bid adapters either empty or with at least one size (but which?)

### PR DESCRIPTION
**Pull request by osulzhenko**
### 🔧 Type of changes
- [ ] new bid adapter
- [ ] bid adapter update
- [ ] new feature
- [ ] new analytics adapter
- [ ] new module
- [ ] module update
- [x] bugfix
- [ ] documentation
- [ ] configuration
- [ ] dependency update
- [ ] tech debt (test coverage, refactorings, etc.)

### ✨ What's the context?
What's the context for the changes?

### 🧠 Rationale behind the change
Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🔎 New Bid Adapter Checklist
- [ ] verify email contact works
- [ ] NO fully dynamic hostnames
- [ ] geographic host parameters are NOT required
- [ ] direct use of HTTP is prohibited - *implement an existing Bidder interface that will do all the job*
- [ ] if the ORTB is just forwarded to the endpoint, use the generic adapter - *define the new adapter as the alias of the generic adapter*
- [ ] cover an adapter configuration with an integration test

### 🧪 Test plan
How do you know the changes are safe to ship to production?

### 🏎 Quality check
- [ ] Are your changes following [our code style guidelines](https://github.com/prebid/prebid-server-java/blob/master/docs/developers/code-style.md)?
- [ ] Are there any breaking changes in your code?
- [ ] Does your test coverage exceed 90%?
- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

### CODE REVIEW

**Review by CTMBNara — APPROVED** [review]

File: src/main/java/org/prebid/server/bidder/ix/IxBidder.java [hunk 1]
```diff
@@ -142,16 +143,18 @@ private UpdateResult<Banner> modifyImpBanner(Banner banner) {
         if (banner == null) {
             return UpdateResult.unaltered(null);
         }
-
-        final List<Format> formats = banner.getFormat();
+        final List<Format> formats = ListUtils.emptyIfNull(banner.getFormat()).stream()
+                .filter(Objects::nonNull)
+                .toList();
```
Comment (CTMBNara) [inline src/main/java/org/prebid/server/bidder/ix/IxBidder.java]: No need for this filter. See `ImpValidator.validateFormat`

**Review by CTMBNara — CHANGES_REQUESTED** [review]

File: src/main/java/org/prebid/server/bidder/ix/IxBidder.java (hunk 1 above)
Comment (osulzhenko) [reply src/main/java/org/prebid/server/bidder/ix/IxBidder.java]: I agree, overengineered here, removed

**Review by Lightwood13 — APPROVED** [review]

**Review by CTMBNara — APPROVED** [review]
